// <auto-generated />
using System;
using AirportRESRfulApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirportRESRfulApi.DAL.Migrations
{
    [DbContext(typeof(AirportContext))]
    [Migration("20180714101636_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartureId");

                    b.HasKey("Id");

                    b.HasIndex("DepartureId")
                        .IsUnique();

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Departure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DepartureTime");

                    b.Property<int>("FlightId");

                    b.Property<string>("FlightNumber");

                    b.HasKey("Id");

                    b.HasIndex("FlightId")
                        .IsUnique();

                    b.ToTable("Departures");
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivalTime");

                    b.Property<string>("DeparturePoint")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DepartureTime");

                    b.Property<string>("DestinationPoint")
                        .HasMaxLength(50);

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("CrewId");

                    b.Property<int>("Experience");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.HasIndex("CrewId")
                        .IsUnique();

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Plane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartureId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("ReleaseDate");

                    b.HasKey("Id");

                    b.HasIndex("DepartureId")
                        .IsUnique();

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.PlaneType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<string>("Model");

                    b.Property<int>("PlaneId");

                    b.Property<int>("Range");

                    b.Property<int>("Seats");

                    b.Property<TimeSpan>("ServiceLife");

                    b.HasKey("Id");

                    b.HasIndex("PlaneId")
                        .IsUnique();

                    b.ToTable("PlaneTypes");
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Stewardess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("CrewId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.ToTable("Stewardesses");
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FlightId");

                    b.Property<string>("FlightNumber");

                    b.Property<bool>("IsSold");

                    b.Property<int>("PlaseNumber");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Crew", b =>
                {
                    b.HasOne("AirportRESRfulApi.DAL.Models.Departure", "Departure")
                        .WithOne("Crew")
                        .HasForeignKey("AirportRESRfulApi.DAL.Models.Crew", "DepartureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Departure", b =>
                {
                    b.HasOne("AirportRESRfulApi.DAL.Models.Flight", "Flight")
                        .WithOne("Departure")
                        .HasForeignKey("AirportRESRfulApi.DAL.Models.Departure", "FlightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Pilot", b =>
                {
                    b.HasOne("AirportRESRfulApi.DAL.Models.Crew", "Crew")
                        .WithOne("Pilot")
                        .HasForeignKey("AirportRESRfulApi.DAL.Models.Pilot", "CrewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Plane", b =>
                {
                    b.HasOne("AirportRESRfulApi.DAL.Models.Departure", "Departure")
                        .WithOne("Plane")
                        .HasForeignKey("AirportRESRfulApi.DAL.Models.Plane", "DepartureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.PlaneType", b =>
                {
                    b.HasOne("AirportRESRfulApi.DAL.Models.Plane")
                        .WithOne("PlaneType")
                        .HasForeignKey("AirportRESRfulApi.DAL.Models.PlaneType", "PlaneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Stewardess", b =>
                {
                    b.HasOne("AirportRESRfulApi.DAL.Models.Crew", "Crew")
                        .WithMany("Stewardesses")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AirportRESRfulApi.DAL.Models.Ticket", b =>
                {
                    b.HasOne("AirportRESRfulApi.DAL.Models.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
